### ISSUE TITLE
TypeError: kwargs_from_env() got an unexpected keyword argument 'ssl_version'

### ISSUE THREAD

**Issue by fahdmirza** [ragapp/ragapp#15] opened 2024-05-25 00:17 UTC
While trying to run this application with Ollama, getting following error. This happens whether Ollama is already installed or not. 

(raggapp) ubuntu@ip-10-218-240-121:~/ragapp$ uname -a
Linux ip-10-218-240-121 6.5.0-1020-aws #20~22.04.1-Ubuntu SMP Wed May  1 16:10:50 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
(raggapp) ubuntu@ip-10-218-240-121:~/ragapp$

(raggapp) ubuntu@ip-10-218-240-121:~/ragapp$ MODEL=llama3 OLLAMA_BASE_URL=http://host.docker.internal:11434 docker-compose up
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 200, in perform_command
    project = project_from_options('.', options)
  File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 60, in project_from_options
    return get_project(
  File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 152, in get_project
    client = get_client(
  File "/usr/lib/python3/dist-packages/compose/cli/docker_client.py", line 41, in get_client
    client = docker_client(
  File "/usr/lib/python3/dist-packages/compose/cli/docker_client.py", line 124, in docker_client
    kwargs = kwargs_from_env(environment=environment, ssl_version=tls_version)
TypeError: kwargs_from_env() got an unexpected keyword argument 'ssl_version'
(raggapp) ubuntu@ip-10-218-240-121:~/ragapp$

Thanks.

**Comment by marcusschiesser** [comment] 2024-05-27 08:02
Thanks. We'll have to try to reproduce this on Ubuntu

**Comment by leehuwuj** [comment] 2024-05-27 09:04
Hi @fahdmirza Thanks for letting us know about the problem! It seems like a docker or docker-compose issue, how did you install them?

**Comment by fahdmirza** [comment] 2024-05-27 23:38
I listed the process here https://youtu.be/arcKYZCuSGA?si=9WpxapcPtr9NM-Iy

**Comment by leehuwuj** [comment] 2024-05-28 05:08
Hi @fahdmirza thanks for the information, sorry but i cannot reproduce your issue in my Ubuntu machine. It looks like a docker-compose issue (check this out: https://github.com/docker/docker-py/issues/3194). Can you try using docker-compose v2 instead?

**Comment by marcusschiesser** [comment] 2024-06-04 07:20
Probably caused by outdated docker, closing

**Closed by marcusschiesser** 2024-06-04 07:20 UTC
